### ISSUE TITLE
fix it!

### ISSUE THREAD

**Issue by shoezon** [Prophecized/CrazyCreepers#1]
fix god damn everything with factions and survival. also fix the wurst enchant thing like i told ya to do also you better be a man of you words prop and make the custom shoepick.

**Comment by Prophecized** [comment]
Hi shoezon thank you for the infomation ill look into it asap thank you

**Comment by Prophecized** [comment]
Please list exactly what the issues are

**Comment by shoezon** [comment]
na im too lazy for that just fix the prisons tpa thing because where able to tpa to mines higher then where able to go and we can sell the stuff if you get there

**Comment by shoezon** [comment]
also prop add a profile pic to your github acc because your profile pic is bland

**Comment by Prophecized** [comment]
Tpa is fixed thank you shoezon
